language: go

services:
  - postgresql

before_script:
  - go get -d ./...

env:
  global:
    - PSQL_USER=postgres
    - PSQL_PASSWORD=

script:
  - make build
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOVE_TOKEN