language: go

go:
  - 1.14.4

services:
  - postgresql

before_script:
  - go mod download

env:
  global:
    - PSQL_USER=postgres
    - PSQL_PASSWORD=
    - DATABASE_URL=postgres://postgres@127.0.0.1:5432/uptime_server_service_test
    - DATABASE_NAME=uptime_server_service_test

script:
  - make build
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOVE_TOKEN